/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jksiazkuch;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author valumior
 */
public class ShowPrzepisy extends javax.swing.JDialog {

    private ArrayList<Przepis> przepiss;
    
    /**
     * Creates new form ShowPrzepisy
     */
    public ShowPrzepisy(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        przepisyList.addListSelectionListener(new ListSelectionListener(){

            @Override
            public void valueChanged(ListSelectionEvent e) {
                przepisyListItemSelectionChanged(e);
            }
            
        });
        
        getListData(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        przepisyUlubionesCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        przepisyList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        przepisSkladnikiList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        skladnikWartosciOdzywczeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        przepisNazwaLabel = new javax.swing.JLabel();
        przepisKalorieLabel = new javax.swing.JLabel();
        przepisTluszczeCalkowiteLabel = new javax.swing.JLabel();
        przepisTluszczeNasyconeLabel = new javax.swing.JLabel();
        przepisTluszczeNienasyconeLabel = new javax.swing.JLabel();
        przepisCholesterolLabel = new javax.swing.JLabel();
        przepisSodLabel = new javax.swing.JLabel();
        przepisWeglowodanyLabel = new javax.swing.JLabel();
        przepisBlonnikLabel = new javax.swing.JLabel();
        przepisCukryLabel = new javax.swing.JLabel();
        przepisBialkaLabel = new javax.swing.JLabel();
        przepisCzasPrzygotowaniaLabel = new javax.swing.JLabel();
        przepisTrudnosclabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        przepisyPrzyrzadzenieTextEdit = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        przepisyUlubionesCheckBox.setText("czy ulubione?");
        przepisyUlubionesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przepisyUlubionesCheckBoxActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(przepisyList);

        jScrollPane2.setViewportView(przepisSkladnikiList);

        jLabel6.setText("Sod (mg):");

        jLabel7.setText("Weglowodany (mg):");

        jLabel8.setText("w tym blonnik:");

        jLabel9.setText("w tym cukry:");

        jLabel10.setText("Bialka (mg):");

        skladnikWartosciOdzywczeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skladnikWartosciOdzywczeLabel.setText("Wartosci odzywcze potrawy");

        jLabel1.setText("Kalorie (cal):");

        jLabel2.setText("Tluszcze calkowite (mg):");

        jLabel3.setText("w tym Tluszcze Nasycone:");

        jLabel4.setText("w tym Tluszcze Nienasycone:");

        jLabel5.setText("Cholesterol (mg):");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Skladniki");

        jLabel12.setText("Czas przygotowania:");

        przepisNazwaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        przepisTrudnosclabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        przepisyPrzyrzadzenieTextEdit.setColumns(20);
        przepisyPrzyrzadzenieTextEdit.setRows(5);
        jScrollPane4.setViewportView(przepisyPrzyrzadzenieTextEdit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(przepisyUlubionesCheckBox)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(przepisNazwaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(przepisCzasPrzygotowaniaLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(przepisTrudnosclabel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(skladnikWartosciOdzywczeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(przepisCholesterolLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(przepisTluszczeNienasyconeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(przepisTluszczeNasyconeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(przepisCukryLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(przepisBlonnikLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(przepisKalorieLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(przepisTluszczeCalkowiteLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(przepisBialkaLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(przepisSodLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(przepisWeglowodanyLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(skladnikWartosciOdzywczeLabel)
                            .addComponent(przepisNazwaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(przepisKalorieLabel)
                            .addComponent(przepisTrudnosclabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(przepisTluszczeCalkowiteLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(przepisTluszczeNasyconeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(przepisTluszczeNienasyconeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(przepisCholesterolLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(przepisSodLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(przepisWeglowodanyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(przepisBlonnikLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(przepisCukryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(przepisBialkaLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 88, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(przepisCzasPrzygotowaniaLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(przepisyUlubionesCheckBox))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void przepisyUlubionesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przepisyUlubionesCheckBoxActionPerformed
        getListData(przepisyUlubionesCheckBox.isSelected());
    }//GEN-LAST:event_przepisyUlubionesCheckBoxActionPerformed

    private void getListData(boolean fav){
        
        Connection con = null;
        try{
            Class.forName("org.sqlite.JDBC");
            try{
                con = DriverManager.getConnection("jdbc:sqlite:../DB/cookbook.db");
                Statement state = con.createStatement();
            
                przepiss = Przepis.getObjects(state, fav);
                przepisyList.setListData(przepiss.toArray());
            }
            catch(SQLException e){
                System.out.println(e.getMessage());
            }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        finally{
            try{
                con.close();
            }
            catch(SQLException e){
                System.out.println(e.getMessage());
            }
        }
    }
    
    private void przepisyListItemSelectionChanged(ListSelectionEvent e){
        this.przepisSkladnikiList.setListData(new Object[0]);
        this.przepisyPrzyrzadzenieTextEdit.setText("");

        this.przepisNazwaLabel.setText("");
        this.przepisTrudnosclabel.setText("");
        this.przepisCzasPrzygotowaniaLabel.setText("");

        this.przepisBialkaLabel.setText("");
        this.przepisBlonnikLabel.setText("");
        this.przepisCholesterolLabel.setText("");
        this.przepisCukryLabel.setText("");
        this.przepisKalorieLabel.setText("");
        this.przepisSodLabel.setText("");
        this.przepisTluszczeCalkowiteLabel.setText("");
        this.przepisTluszczeNasyconeLabel.setText("");
        this.przepisTluszczeNienasyconeLabel.setText("");
        this.przepisWeglowodanyLabel.setText("");

        Przepis przepis = (Przepis)this.przepisyList.getSelectedValue();
        this.loadPrzepisData(przepis);
    }

    private void loadPrzepisData(Przepis przepis) {
        this.przepisyPrzyrzadzenieTextEdit.setText(przepis.getInstrukcja());
        this.przepisNazwaLabel.setText(przepis.getNazwa());
        this.przepisCzasPrzygotowaniaLabel.setText(Integer.toString(przepis.getCzasPrzygotowania()) + " minut");

        switch(przepis.getTrudnosc()) {
            case Latwe:
                this.przepisTrudnosclabel.setText("ŁATWE");
                break;
            case Srednie:
                this.przepisTrudnosclabel.setText("ŚREDNIE");
                break;
            case Trudne:
                this.przepisTrudnosclabel.setText("TRUDNE");
                break;
            case MistrzKuchni:
                this.przepisTrudnosclabel.setText("MISTRZ KUCHNI");
                break;
            default:
                break;
        }

        double kalorieTotal = 0, tluszcze_calkowiteTotal = 0, tluszcze_nasyconeTotal = 0, tluszcze_nienasyconeTotal = 0,
            cholesterolTotal = 0, sodTotal = 0, weglowodanyTotal = 0, blonnikTotal = 0, cukryTotal = 0, bialkaTotal = 0;

        ArrayList<String> skladniki = new ArrayList<>();
        
        for(PrzepisSkladnik skladnik : przepis.getSkladniki()) {
            double ratio = 1;
            if(skladnik.getSkladnik().getMiara() == Skladnik.Miara.Mililitry || skladnik.getSkladnik().getMiara() == Skladnik.Miara.Gramy) {
                ratio = 100;
            }

            if(skladnik.getSkladnik().getMiara() == Skladnik.Miara.Mililitry)
                skladniki.add(skladnik.getSkladnik().getNazwa() + " " + Integer.toString(skladnik.getLiczba()) + "ml");
            else if(skladnik.getSkladnik().getMiara() == Skladnik.Miara.Gramy)
                skladniki.add(skladnik.getSkladnik().getNazwa() + " " + Integer.toString(skladnik.getLiczba()) + "g");
            else
                skladniki.add(skladnik.getSkladnik().getNazwa() + " " + Integer.toString(skladnik.getLiczba()) + " szt.");

            ratio = skladnik.getLiczba() / ratio;

            WartosciOdzywcze wartosciOdzywcze = skladnik.getSkladnik().getWartosciOdzywcze();
            kalorieTotal += wartosciOdzywcze.getKalorie() * ratio;
            tluszcze_calkowiteTotal += wartosciOdzywcze.getTluszczeCalkowite() * ratio;
            tluszcze_nasyconeTotal += wartosciOdzywcze.getTluszczeNasycone() * ratio;
            tluszcze_nienasyconeTotal += wartosciOdzywcze.getTluszczeNienasycone() * ratio;
            cholesterolTotal += wartosciOdzywcze.getCholesterol() * ratio;
            sodTotal += wartosciOdzywcze.getSod() * ratio;
            weglowodanyTotal += wartosciOdzywcze.getWeglowodany() * ratio;
            blonnikTotal += wartosciOdzywcze.getBlonnik() * ratio;
            cukryTotal += wartosciOdzywcze.getCukry() * ratio;
            bialkaTotal += wartosciOdzywcze.getBialka() * ratio;
        }
        
        this.przepisSkladnikiList.setListData(skladniki.toArray());

        this.przepisKalorieLabel.setText(Double.toString(kalorieTotal));
        this.przepisTluszczeCalkowiteLabel.setText(Double.toString(tluszcze_calkowiteTotal));
        this.przepisTluszczeNasyconeLabel.setText(Double.toString(tluszcze_nasyconeTotal));
        this.przepisTluszczeNienasyconeLabel.setText(Double.toString(tluszcze_nienasyconeTotal));
        this.przepisCholesterolLabel.setText(Double.toString(cholesterolTotal));
        this.przepisSodLabel.setText(Double.toString(sodTotal));
        this.przepisWeglowodanyLabel.setText(Double.toString(weglowodanyTotal));
        this.przepisBlonnikLabel.setText(Double.toString(blonnikTotal));
        this.przepisCukryLabel.setText(Double.toString(cukryTotal));
        this.przepisBialkaLabel.setText(Double.toString(bialkaTotal));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowPrzepisy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowPrzepisy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowPrzepisy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowPrzepisy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShowPrzepisy dialog = new ShowPrzepisy(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel przepisBialkaLabel;
    private javax.swing.JLabel przepisBlonnikLabel;
    private javax.swing.JLabel przepisCholesterolLabel;
    private javax.swing.JLabel przepisCukryLabel;
    private javax.swing.JLabel przepisCzasPrzygotowaniaLabel;
    private javax.swing.JLabel przepisKalorieLabel;
    private javax.swing.JLabel przepisNazwaLabel;
    private javax.swing.JList przepisSkladnikiList;
    private javax.swing.JLabel przepisSodLabel;
    private javax.swing.JLabel przepisTluszczeCalkowiteLabel;
    private javax.swing.JLabel przepisTluszczeNasyconeLabel;
    private javax.swing.JLabel przepisTluszczeNienasyconeLabel;
    private javax.swing.JLabel przepisTrudnosclabel;
    private javax.swing.JLabel przepisWeglowodanyLabel;
    private javax.swing.JList przepisyList;
    private javax.swing.JTextArea przepisyPrzyrzadzenieTextEdit;
    private javax.swing.JCheckBox przepisyUlubionesCheckBox;
    private javax.swing.JLabel skladnikWartosciOdzywczeLabel;
    // End of variables declaration//GEN-END:variables
}
